Fix bug: exception when certificate key type is OpenSSLDSAPublicKey or BCDSAPublicKey.
Just print "unknown" instead. TODO: extract and print SHA1 for OpenSSLDSAPublicKey and BCDSAPublicKey, it's probably easy.

Crash looks like:
12-01 14:29:11.281 W/About: [] has unknown key class BCDSAPublicKey
12-01 14:29:11.282 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: com.google.android.apps.about, PID: 20879
                                     java.lang.RuntimeException: Unable to create application com.google.android.apps.about.MobileApplication: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5375)
                                         at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1529)
                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                         at android.os.Looper.loop(Looper.java:154)
                                         at android.app.ActivityThread.main(ActivityThread.java:6088)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                      Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                                         at com.google.android.apps.about.common.TextManager.writeTextForPackage(TextManager.java:140)
                                         at com.google.android.apps.about.common.TextManager.generateText(TextManager.java:105)
                                         at com.google.android.apps.about.MobileApplication.onCreate(MobileApplication.java:16)
                                         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5372)
                                         at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1529)
                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                         at android.os.Looper.loop(Looper.java:154)
                                         at android.app.ActivityThread.main(ActivityThread.java:6088)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
12-01 14:29:11.284 W/ActivityManager:   Force finishing activity com.google.android.apps.about/.MobileActivity